# Generated by Django 2.0.4 on 2018-10-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='设备型号', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModbusRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='寄存器名称', max_length=100)),
                ('supported_x03', models.BooleanField(default=True, help_text='是否支持0x03功能码')),
                ('supported_x06', models.BooleanField(default=False, help_text='是否支持0x06功能码')),
                ('address', models.IntegerField(default=0, help_text='地址')),
                ('unit', models.CharField(default='', help_text='单位', max_length=10)),
                ('resolution', models.IntegerField(default=1, help_text='精度, x1, x10, x100')),
                ('signed', models.BooleanField(default=False, help_text='是否有符号')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.ModbusDevice')),
            ],
        ),
    ]
