# Generated by Django 2.0.4 on 2018-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='name',
            field=models.CharField(default='', help_text='设备名称', max_length=30),
        ),
        migrations.AlterField(
            model_name='modbusdevice',
            name='model',
            field=models.CharField(default='', help_text='设备型号', max_length=30),
        ),
    ]
