# Generated by Django 2.0.4 on 2018-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20181003_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusregister',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='单位', max_length=10),
        ),
    ]
