# Generated by Django 2.0.4 on 2018-10-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20181003_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='设备名称', max_length=30)),
                ('model', models.CharField(default='', help_text='设备型号', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置名称', max_length=100)),
                ('bms_model', models.CharField(blank=True, help_text='BMS设备型号', max_length=100)),
                ('bms_can_model', models.CharField(blank=True, help_text='BMS-CAN设备型号', max_length=100)),
                ('bms_can_idx', models.IntegerField(default=0, help_text='BMS-CAN设备索引号')),
                ('bms_can_channel', models.IntegerField(default=0, help_text='BMS-CAN设备通道')),
                ('bms_can_bps', models.CharField(help_text='BMS-CAN设备波特率', max_length=30)),
                ('modbus_model', models.CharField(blank=True, help_text='MODBUS设备型号', max_length=100)),
                ('modbus_can_model', models.CharField(blank=True, help_text='MODBUS-CAN设备型号', max_length=100)),
                ('modbus_can_idx', models.IntegerField(default=0, help_text='MODBUS-CAN设备索引号')),
                ('modbus_can_channel', models.IntegerField(default=0, help_text='MODBUS-CAN设备通道')),
                ('modbus_can_bps', models.CharField(help_text='MODBUS-CAN设备波特率', max_length=30)),
            ],
        ),
    ]
