# Generated by Django 2.0.4 on 2018-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_bmsdevice_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='YaoceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.IntegerField(help_text='modbus 服务器地址')),
                ('tsp', models.DateTimeField(default='2018-01-01 00:00:00', help_text='记录时戳')),
                ('txt', models.TextField(help_text='json数据')),
            ],
        ),
    ]
